import type { FhirRef } from "@sysml-fhir-bridge/model-core";
import type { FhirResource } from "./resources.js";

export type FhirVersion = "4.0.1" | "4.3.0" | "5.0.0";

/**
 * FHIR release adapter boundary (ADR-004: FHIR version is part of the
 * interface contract, never hard-coded into the trace model).
 */
export interface FhirAdapter {
  readonly fhirVersion: FhirVersion;
  /** Canonical base URL used for profiles generated by this deployment. */
  readonly canonicalBase: string;
  profileCanonical(profileName: string): string;
  instanceRef(resource: FhirResource, opts?: { versionId?: string }): FhirRef;
  profileRef(profileName: string, profileVersion: string): FhirRef;
}

export class R5Adapter implements FhirAdapter {
  readonly fhirVersion: FhirVersion = "5.0.0";

  constructor(readonly canonicalBase: string) {}

  profileCanonical(profileName: string): string {
    return `${this.canonicalBase}/StructureDefinition/${profileName}`;
  }

  instanceRef(resource: FhirResource, opts?: { versionId?: string }): FhirRef {
    const ref: FhirRef = {
      standard: "fhir",
      fhirVersion: this.fhirVersion,
      resourceType: resource.resourceType,
      logicalId: resource.id,
    };
    if (opts?.versionId !== undefined) ref.versionId = opts.versionId;
    return ref;
  }

  profileRef(profileName: string, profileVersion: string): FhirRef {
    return {
      standard: "fhir",
      fhirVersion: this.fhirVersion,
      canonical: this.profileCanonical(profileName),
      profileVersion,
    };
  }
}
